language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
notifications:
  email: false
branches:
  only: 
    - master
    - develop
install:
  - npm install
script:
  - CI=false npm run build
  - npm run build-server